### ISSUE TITLE
Interactive console cannot handle £ symbol

### ISSUE THREAD

**Issue by conductiveIT** [conductiveIT/OCR-Pseudocode-to-Python#39]
If there is a £ in a PRINT/INPUT statement, the interactive console fails with a UnicodeDecodeError

**Comment by conductiveIT** [comment]
Exception trace:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "\\svr-lc-file01\tutorhome$\t.ben.foulger\Downloads\OCR-Pseudocode-to-Python-master (4)\OCR-Pseudocode-to-Python-master\OCR_Pseudocode_to_Python_GUI.py", line 87, in readFromProccessOut
    data = self.p.stdout.raw.read(1024).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 2: invalid start byte
